#pragma once

// From glfw3.h
#define INP_MOUSE_BUTTON_1      0
#define INP_MOUSE_BUTTON_2      1
#define INP_MOUSE_BUTTON_3      2
#define INP_MOUSE_BUTTON_4      3
#define INP_MOUSE_BUTTON_5      4
#define INP_MOUSE_BUTTON_6      5
#define INP_MOUSE_BUTTON_7      6
#define INP_MOUSE_BUTTON_8      7
#define INP_MOUSE_BUTTON_LAST   INP_MOUSE_BUTTON_8
#define INP_MOUSE_BUTTON_LEFT   INP_MOUSE_BUTTON_1
#define INP_MOUSE_BUTTON_RIGHT  INP_MOUSE_BUTTON_2
#define INP_MOUSE_BUTTON_MIDDLE INP_MOUSE_BUTTON_3
